BEGIN;

-- PostgreSQL/Neon seed converted from the original MySQL dump.
-- Foreign keys are intentionally omitted because the source data contains
-- references to rows that are not present in the dump.

DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS password_resets CASCADE;
DROP TABLE IF EXISTS passenger_statistics CASCADE;
DROP TABLE IF EXISTS rides CASCADE;
DROP TABLE IF EXISTS vehicles CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS id_numbers CASCADE;
DROP TABLE IF EXISTS admin_users CASCADE;

DROP FUNCTION IF EXISTS set_updated_at() CASCADE;

CREATE TABLE admin_users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE bookings (
  booking_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ride_id INTEGER NOT NULL,
  booking_status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE id_numbers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  faculty_id_num VARCHAR(50),
  student_id_num VARCHAR(50)
);

CREATE TABLE passenger_statistics (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  day_of_week VARCHAR(20) NOT NULL CHECK (day_of_week IN ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday')),
  time_slot VARCHAR(20) NOT NULL,
  bookings_count INTEGER DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE password_resets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  token VARCHAR(255) NOT NULL,
  expires_at TIMESTAMP NOT NULL
);

CREATE TABLE payments (
  payment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ride_id INTEGER,
  amount NUMERIC(10, 2) NOT NULL,
  payment_method VARCHAR(20) NOT NULL,
  status VARCHAR(20) NOT NULL,
  phone_number VARCHAR(20) NOT NULL,
  user_id INTEGER NOT NULL,
  payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE rides (
  ride_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plate_number VARCHAR(25),
  driver_id INTEGER,
  start_location VARCHAR(255) NOT NULL,
  end_location VARCHAR(255) NOT NULL,
  status VARCHAR(20) NOT NULL CHECK (status IN ('In Queue', 'Scheduled', 'Inactive', 'Done', 'Cancelled')),
  fare NUMERIC(10, 2) NOT NULL,
  waiting_time TIME NOT NULL,
  time_range VARCHAR(50),
  seat_status VARCHAR(15)
);

CREATE TABLE users (
  user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  username VARCHAR(100),
  email VARCHAR(191) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  phone_number VARCHAR(20),
  user_type VARCHAR(20),
  profile_picture VARCHAR(255),
  id_number VARCHAR(255),
  driver_id INTEGER
);

CREATE TABLE vehicles (
  vehicle_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  driver_id INTEGER,
  capacity INTEGER NOT NULL,
  plate_number VARCHAR(1234) NOT NULL
);

CREATE UNIQUE INDEX admin_users_username_key ON admin_users (LOWER(username));
CREATE INDEX bookings_ride_id_idx ON bookings (ride_id);
CREATE UNIQUE INDEX id_numbers_faculty_id_num_key ON id_numbers (faculty_id_num) WHERE faculty_id_num IS NOT NULL;
CREATE UNIQUE INDEX id_numbers_student_id_num_key ON id_numbers (student_id_num) WHERE student_id_num IS NOT NULL;
CREATE INDEX password_resets_user_id_idx ON password_resets (user_id);
CREATE UNIQUE INDEX password_resets_token_key ON password_resets (token);
CREATE INDEX payments_ride_id_idx ON payments (ride_id);
CREATE INDEX payments_user_id_idx ON payments (user_id);
CREATE INDEX rides_driver_id_idx ON rides (driver_id);
CREATE INDEX rides_plate_number_idx ON rides (plate_number);
CREATE UNIQUE INDEX users_email_key ON users (LOWER(email));
CREATE UNIQUE INDEX users_username_key ON users (LOWER(username)) WHERE username IS NOT NULL;
CREATE UNIQUE INDEX users_driver_id_key ON users (driver_id) WHERE driver_id IS NOT NULL;
CREATE INDEX users_name_idx ON users (name);
CREATE INDEX vehicles_driver_id_idx ON vehicles (driver_id);
CREATE UNIQUE INDEX vehicles_plate_number_key ON vehicles (plate_number);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER passenger_statistics_set_updated_at
BEFORE UPDATE ON passenger_statistics
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

INSERT INTO admin_users (id, username, password) VALUES
  (1, 'Admin', '$2b$10$JWVshbB0QiOFssRbxIO7qewhPE/KH4FngfAs5SQugFfK6WVPm9VJm'),
  (3, 'admin2', '$2b$10$JWVshbB0QiOFssRbxIO7qewhPE/KH4FngfAs5SQugFfK6WVPm9VJm'),
  (4, 'admin3', '$2b$10$JWVshbB0QiOFssRbxIO7qewhPE/KH4FngfAs5SQugFfK6WVPm9VJm');

INSERT INTO bookings (booking_id, ride_id, booking_status, created_at) VALUES
  (1, 10077, 'BOOKED', '2024-12-18 17:54:33'),
  (2, 10078, 'BOOKED', '2024-12-18 18:01:14'),
  (3, 10079, 'BOOKED', '2024-12-18 18:43:05'),
  (4, 10079, 'BOOKED', '2024-12-18 18:47:48'),
  (5, 10078, 'BOOKED', '2024-12-19 00:36:28');

INSERT INTO id_numbers (id, faculty_id_num, student_id_num) VALUES
  (1, '2351426', NULL),
  (2, NULL, '2222725'),
  (3, NULL, '2234223'),
  (4, NULL, '2222723'),
  (5, NULL, '22224982'),
  (6, '2978909', NULL);

INSERT INTO passenger_statistics (id, day_of_week, time_slot, bookings_count, updated_at) VALUES
  (1, 'Monday', '6:00 AM - 7:00 AM', 15, '2024-12-10 02:58:00'),
  (2, 'Monday', '7:00 AM - 8:00 AM', 25, '2024-12-10 02:58:00'),
  (3, 'Tuesday', '6:00 AM - 7:00 AM', 10, '2024-12-10 02:58:00'),
  (4, 'Tuesday', '7:00 AM - 8:00 AM', 30, '2024-12-10 02:58:00'),
  (5, 'Saturday', '9:00 AM - 10:00 AM', 5, '2024-12-10 02:58:00');

INSERT INTO payments (payment_id, ride_id, amount, payment_method, status, phone_number, user_id, payment_date) VALUES
  (26, 1059, 13.00, 'cash', 'pending', '0', 24, '2024-12-11 10:01:51'),
  (27, 1053, 13.00, 'Maya', 'pending', '2147483647', 24, '2024-12-11 10:01:51'),
  (28, 1048, 18.00, 'cash', 'pending', '0', 27, '2024-12-11 10:01:51'),
  (29, 1048, 18.00, 'cash', 'pending', '0', 27, '2024-12-11 10:01:51'),
  (30, 1018, 18.00, 'cash', 'pending', '0', 31, '2024-12-12 14:40:38'),
  (31, 1058, 18.00, 'cash', 'pending', '0', 32, '2024-12-12 14:42:54'),
  (32, 1059, 18.00, 'cash', 'pending', '0', 37, '2024-12-13 00:02:16'),
  (33, 10078, 18.00, 'cash', 'pending', '0', 36, '2024-12-19 00:36:30');

INSERT INTO rides (ride_id, plate_number, driver_id, start_location, end_location, status, fare, waiting_time, time_range, seat_status) VALUES
  (10080, 'YAA 3508', 39, 'Igorot Garden', 'Phase 1', 'In Queue', 13.00, '00:15:00', '2024-12-19 01:00-01:15', '0/23'),
  (10079, 'YAA 3508', 39, 'Igorot Garden', 'Barangay Hall', 'Done', 12.00, '00:15:00', '2024-12-19 00:45-01:00', '0/23'),
  (10078, 'YAA 3508', 39, 'Barangay Hall', 'SM Baguio', 'Done', 12.00, '00:15:00', '2024-12-19 00:30-00:45', '1'),
  (10077, 'YAA 3508', 39, 'Igorot Garden', 'SLU Mary Heights', 'Done', 13.00, '00:15:00', '2024-12-19 00:15-00:30', '0/23'),
  (10076, 'YAA 3508', 39, 'Igorot Garden', 'SLU Mary Heights', 'Done', 13.00, '00:15:00', '2024-12-18 23:15-23:30', '0/23');

INSERT INTO users (user_id, name, username, email, password_hash, phone_number, user_type, profile_picture, id_number, driver_id) VALUES
  (28, 'Aisea Marie Factor', 'Aisea', 'asieamarie@gmail.com', '$2b$10$8wSIRmu0rB8mecY6TsA/7uNTBaViMYvuVfaEteiRS5lakMOTyXJxu', '9183724988', 'Student', '/uploads/profile_pictures/1733847649371-4043260_avatar_male_man_portrait_icon.ico', NULL, NULL),
  (30, 'Martin Kapitan', 'Martin', 'kapitanmartin@gmail.com', '$2b$10$6p4PWt5901vHTalFLmlEdOTCiomaEYLk/zRvMtD8zB7RZiByL5u1y', '9234693982', 'Driver', NULL, NULL, NULL),
  (36, 'Claude API', 'Claude', 'claudeai@gmail.com', '$2b$10$6MtXay.RGLeDo/AWvdrmHuSIVOIIU7tngsKxYePLhdFiCB7eGivM2', '9845345678', 'Student', '/uploads/profile_pictures/1734534060201-Profile-YGN_1.png', '2222723', NULL),
  (38, 'Karding Kenkoy', 'Karding', '', '$2b$10$NvtxuNTJQ3nmPC1TBQzgtu5OZvM0Rdos9ZmbP7NjLeHuJ1nWsexHq', NULL, 'Driver', NULL, NULL, 103),
  (39, 'Rolando Morzoe', 'Rolando', 'rolandospy@gmail.com', '$2b$10$AcPYFZ87FlEow0ggDupZyeTTa3llokZTQc19yoShBbyJ5fnvZO3B6', '9483276877', 'Driver', NULL, '', 104);

INSERT INTO vehicles (vehicle_id, driver_id, capacity, plate_number) VALUES
  (8, 39, 23, 'YAA 3508');

SELECT setval(pg_get_serial_sequence('admin_users', 'id'), COALESCE((SELECT MAX(id) FROM admin_users), 1), true);
SELECT setval(pg_get_serial_sequence('bookings', 'booking_id'), COALESCE((SELECT MAX(booking_id) FROM bookings), 1), true);
SELECT setval(pg_get_serial_sequence('id_numbers', 'id'), COALESCE((SELECT MAX(id) FROM id_numbers), 1), true);
SELECT setval(pg_get_serial_sequence('passenger_statistics', 'id'), COALESCE((SELECT MAX(id) FROM passenger_statistics), 1), true);
SELECT setval(pg_get_serial_sequence('password_resets', 'id'), COALESCE((SELECT MAX(id) FROM password_resets), 1), true);
SELECT setval(pg_get_serial_sequence('payments', 'payment_id'), COALESCE((SELECT MAX(payment_id) FROM payments), 1), true);
SELECT setval(pg_get_serial_sequence('rides', 'ride_id'), COALESCE((SELECT MAX(ride_id) FROM rides), 1), true);
SELECT setval(pg_get_serial_sequence('users', 'user_id'), COALESCE((SELECT MAX(user_id) FROM users), 1), true);
SELECT setval(pg_get_serial_sequence('vehicles', 'vehicle_id'), COALESCE((SELECT MAX(vehicle_id) FROM vehicles), 1), true);

COMMIT;
